version: "3"
services:
  db:
    image: postgres:15.1
    container_name: chatloja_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=chatloja
    cap_add:
      - SYS_NICE # disables logs `mbind: Operation not permitted`
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root", "-d", "chatloja"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    profiles:
      - default
      - infra
